### PR TITLE
[gsoc24] Add a proposal on llvm.org revamp.

### PR DESCRIPTION
**Pull request by vgvassilev**
This has come up couple of times as discussion in the corridors at the LLVM Dev meetings. I am not sure who's responsible about this area and I hope I am not overstepping. I am willing to do some of the mentoring work but I'd like to find at least one or two more co-mentors.

If we have an agreement that's a good GSoC project I will open a thread on discourse.

cc: @asl, @tlattner

### CODE REVIEW

**Comment by asl** [comment]
@vgvassilev Go for it! :)

**Comment by aemerson** [comment]
This sounds like a great idea. I would also suggest somewhere that the new design should keep accessibility in mind, how does it fare for those with visual impairment/using screen readers etc. I'm not sure how well the current website does on that front.

**Comment by asl** [comment]
> I'm not sure how well the current website does on that front.

The current website has all kinds of issues including mobile version, accessibility, etc. I think that most modern frameworks take care of this automatically. But it does not hurt to mention this explicitly. And at least do some checks to understand where we are.

**Comment by MaskRay** [comment]
Thanks for this proposal. The llvm.org has been the most "stable" component of the project. It deserves a remodel:)

https://web.archive.org/web/20040503004454/https://llvm.org/

**Comment by vgvassilev** [comment]
I am also interested in finding a co-mentor for this project.

**Comment by tlattner** [comment]
While I do believe llvm.org needs a revamp and have been thinking about this for almost 10 years, I'm worried this is not a good GSOC project given scope and intimate knowledge of the project required. However, I am trying to keep an open mind and see what applicants apply. I have some very strong opinions about it and could help mentor.

**Pull request merged**
