### PR TITLE
Updates for 15.0.0 release

### PR DESCRIPTION
**Pull request by tru**

### CODE REVIEW

**Review by asl — APPROVED** [review]
LGTM, thanks!

**Comment by tru** [comment]
Seems like it needs to be manually deployed - I only have access to the releases machine - so I don't think I can update the main www site. Can someone with access fix that?

**Comment by sylvestre** [comment]
it used to be automatic?!

**Comment by tru** [comment]
My changes are at least not up on llvm.org yet and 4 days are hopefully enough time for caches to invalidate :)

**Pull request merged**
